<?php declare(strict_types=1)
/** var \Magento\Framework\View\Element\Template $block */
?>
<p>asdffdaa</p>
  <!-- <script type="text/x-magento-init">
    {
        "*":{
          "Magento_Ui/js/core/app":{
            "components": {
              "startSimple": {
                "component": "Customer_Require/js/requireweb"
              }
            }
          }
        }

    }
  </script>
  <div data-bind="scope: 'startSimple'">
    <table data-bind="foreach: viewModel.exchange_rates">
        <tr>
            <td data-bind="text: currency_to"></td>
            <td data-bind="text: rate"></td>
        </tr>
    </table>
</div> -->

