<h1>Edit Project</h1>

<form method="post" id="edit-project-form">
    <?php $projectData = $block->getProjectData(); ?>
    <?php if ($projectData): ?>
        
        <input type="hidden" name="entity_id" value="<?php echo $projectData->getEntityId(); ?>">

        <label for="description">Description:</label>
        <input type="text" name="description" id="description" value="<?php echo $projectData->getDescription(); ?>"><br>
        
        <label for="customerId">Customer ID:</label>
        <input type="text" name="customer_id" id="customer_id" value="<?php echo $projectData->getCustomerId(); ?>" readonly><br>

        <label for="status">Status:</label>
        <select name="status" id="status">
            <option value="1" <?php echo $projectData->getStatus() == '1' ? 'selected' : ''; ?>>Enable</option>
            <option value="0" <?php echo $projectData->getStatus() == '0' ? 'selected' : ''; ?>>Disable</option>
        </select><br>
    <?php endif; ?>

    <input type="submit" value="Save">
</form>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#edit-project-form').submit(function(event) {
                event.preventDefault(); 
                // console.log('hello');
                var formData = $(this).serialize();
                // console.log(formData);
                $.ajax({
                    type: 'POST',
                    url: '/custaccounttab/index/save',
                    data: formData,
                    dataType: 'json',
                    success: function(response) {
                        if (response.success) {
                            alert('Project data saved successfully.');
                        } else {
                            alert('Error: ' + response.error);
                        }
                    },
                    error: function() {
                        alert('An error occurred while saving project data.');
                    }
                });
            });
        });
    });
</script>
