<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Extended Product Grid with Editor for Magento 2
 */
/** @var $block \Amasty\Pgrid\Block\Adminhtml\Product\Grid\TierPrice\Content */
/** @var \Magento\Framework\Escaper $escaper */

    $htmlId = $block->getElement()->getHtmlId();
    $htmlClass = $block->getElement()->getClass();
    $htmlName = $block->getElement()->getName();
    $priceValueValidation = $block->getPriceValidation('validate-greater-than-zero');
?>

<div class="field" id="attribute-<?= $escaper->escapeHtmlAttr($htmlId) ?>-container" data-attribute-code="<?= $escaper->escapeHtmlAttr($htmlId) ?>"
     data-apply-to="<?= $escaper->escapeHtmlAttr($block->getApplyToJson())?>">
    <label class="label">
        <?= $escaper->escapeHtml($block->getElement()->getLabel()) ?>
    </label>
    <div class="control ampgrid-prices">
        <form action="#" id="tier-prices-form">
            <table class="admin__control-table ampaction-table-container">
                <thead>
                <tr>
                    <th class="col-websites"><?= $escaper->escapeHtml(__('Website')) ?></th>
                    <th class="col-customer-group"><?= $escaper->escapeHtml(__('Customer Group')) ?></th>
                    <th class="col-qty required"><?= $escaper->escapeHtml(__('Quantity')) ?></th>
                    <th class="col-price-value-type required"><?= $escaper->escapeHtml(__('Price')) ?></th>
                    <th class="col-price required"></th>
                    <th class="col-delete"></th>
                </tr>
                </thead>
                <tbody id="<?= $escaper->escapeHtmlAttr($htmlId) ?>_container">
                <!-- ko template: getTemplate() --><!-- /ko -->
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="6" class="col-actions-add">
                        <button data-bind="click: addRow"
                                role="button"
                                type="button"
                                title="<?= $escaper->escapeHtml(__('Add')) ?>"
                                aria-label="<?= $escaper->escapeHtml(__('Add')) ?>">
                            <?= $escaper->escapeHtml(__('Add')) ?>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "tier-prices": {
                        "component": "Amasty_Pgrid/js/grid/modal/tier-prices",
                        "htmlClass": "<?= /* @noEscape */ $htmlClass ?>",
                        "websites": <?= /* @noEscape */ $block->getWebsitesJson() ?>,
                        "groups": <?= /* @noEscape */ $block->getGroupsJson() ?>,
                        "htmlName": "<?= /* @noEscape */ $htmlName ?>",
                        "priceValueValidationClass": "<?= /* @noEscape */ $priceValueValidation ?>",
                        "priceTypes": <?= /* @noEscape */ $block->getPriceValueTypesJson() ?>,
                        "deleteButtonTitle": "<?= $escaper->escapeHtml(__("Delete Item")) ?>"
                    }
                }
            }
        }
    }
</script>

<script>
    require(['jquery', 'ko', 'uiRegistry'], function ($, ko, registry) {
        $('body').trigger('contentUpdated');

        registry.get('tier-prices', function (component) {
            ko.applyBindings(component, $('.ampgrid-prices')[0]);
        });
    });
</script>

