<form  action="/rfq/index/save" method="post">
<input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>" />

    <div class="field">
        <label for="first_name">First Name</label>
        <input type="text" id="first_name" name="first_name" required />
    </div>

    <div class="field">
        <label for="last_name">Last Name</label>
        <input type="text" id="last_name" name="last_name" required />
    </div>

    <div class="field">
        <label for="street_address">Street Address</label>
        <input type="text" id="street_address" name="street_address" required />
    </div> 

    <div class="field">
        <label for="zip_code">Zip/Postal Code</label>
        <input type="text" id="zip_code" name="zip_code" required />
    </div> 

    <div class="field">
        <label for="apt_suite">Apt / Suite / Bldg </label>
        <input type="text" id="apt" name="apt" />
    </div>

    <div class="field">
        <label for="city">City</label>
        <input type="text" id="city" name="city" required />
    </div>

    <div class="field">
        <label for="country">Country</label>
        <input type="text" id="country" name="country" required />
    </div>

    <div class="field">
        <label for="state">State/Province</label>
        <input type="text" id="state" name="state" required />
    </div>

    <div class="field">
        <label for="phone">Phone Number</label>
        <input type="tel" id="phone" name="phone_number" required />
    </div>

    <div class="field">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" required />
    </div>

    <div class="field">
        <label for="quantity">Quantity</label>
        <input type="number" id="quantity" name="quantity" required />
    </div>

    <div class="field">
        <label for="product_id">Product ID</label>
        <input type="number" id="product_id" name="product_id" required />
    </div> 

    <div class="field">
        <label for="target_price">Target Price (US $)</label>
        <input type="number" id="target_price" name="target_price" required />
    </div> 

    <div class="field">
        <label for="comment">Comment</label>
        <textarea id="comment" name="comment"></textarea>
    </div>

    <div class="actions-toolbar">
            <button type="submit" class="submit-action">
                <span>Submit</span>
            </button>
    </div>
</form>
